### PR TITLE
Made some UI changes

### PR DESCRIPTION
**Pull request by ingridt123**
- Only selected course list and description box scrolls in right column
- Dynamically updates course search list and schedule height (when window resized)
- Removed some commented code that is unnecessary
- Margin between buttons when put in rows in toolbar

### CODE REVIEW

**Review by raxod502 — APPROVED** [review]
🌀

**Comment by raxod502** [comment]
You might consider creating separate branches for each pull request so that you can make more than one without the changes becoming entangled.

**Comment by ingridt123** [comment]
Ok thanks for the feedback!
So I would make the pull requests from the separate branches and then separately merge them into the master branches of this repo and my forked repo?

**Comment by raxod502** [comment]
Well, you aren't going to be merging the pull requests (`fork/feature-branch` -> `upstream/master`). That is my job. And after a pull request is merged, you don't need to do anything other than pull the latest master (`upstream/master` -> `fork/master`) and then base future pull requests on that branch (`fork/master` -> `fork/feature-branch`). I would advise finding some resources to learn about the standard pull request workflow.

**Pull request merged**
