### PR TITLE
Turn links in course descriptions into anchor tags in the DOM

### PR DESCRIPTION
**Pull request by marcos-acosta**
**Description**
I noticed that links appear as literal anchor tags in course descriptions, especially for PE classes. I figured it would be convenient for users if those links were displayed as actual anchor tags.

**Changes**
- Add CSS for anchor tag in `course-details.pcss`
- Add a function for using regex to parse raw anchor tags in course descriptions
- Set description with `.innerHTML()` instead of `.textContent()`
  - `innerHTML` is less efficient than `textContent`, but I imagine the performance drop is marginal

### CODE REVIEW

**Comment by kwshi** [comment]
Nice idea!  Can I ask-- why is innerHTML needed if you're already making a regexp parser for anchor tags?  Or vice versa?

**Comment by marcos-acosta** [comment]
Thanks! You were right, it doesn't need the regex parser, setting `innerHTML` to the raw course description displays links properly too

**Comment by kwshi** [comment]
By the way, can you tell me an example of such a course (with anchor tag in description) so that I can test out & compare?

**Comment by marcos-acosta** [comment]
Yeah! Almost all of the PEs have a link to the CMS athletics webpage, e.g. ping pong

**Comment by kwshi** [comment]
Looks nice!

**Review by kwshi — APPROVED** [review]

**Pull request merged**
