### PR TITLE
Added conflicting courses toggle next to closed courses toggle

### PR DESCRIPTION
**Pull request by AmitHarlev**

### CODE REVIEW

**Comment by AmitHarlev** [comment]
I tried to squash the commits before doing the pull request but it evidently did not work.

**Comment by raxod502** [comment]
Can you make it possible to only filter courses that conflict with starred courses?

**Comment by AmitHarlev** [comment]
Yes, but I don't know how you would want the UI for that to look. There isn't really more space where I put this checkbox for more settings.

**Comment by raxod502** [comment]
What about a drop-down menu instead of a checkbox?

**Comment by AmitHarlev** [comment]
This is ready to be reviewed.

**Comment by AmitHarlev** [comment]
Resolves #60

**Comment by raxod502** [comment]
Looks like we've got some merge conflicts here.

**Comment by AmitHarlev** [comment]
This is ready to be reviewed.

**Review by raxod502 — APPROVED** [review]
:100:

**Pull request merged**
