### PR TITLE
Updated to newest version of Ionicons

### PR DESCRIPTION
**Pull request by ingridt123**

### CODE REVIEW

**Review by raxod502 — APPROVED** [review]
:arrow_double_up:

**Comment by raxod502** [comment]
upgrading things is always fine, but I was just wondering if this fixes a specific bug or adds functionality?

**Comment by AmitHarlev** [comment]
The add icons disappeared in the course search list. It was working earlier today. Could this have caused that?

**Comment by ingridt123** [comment]
Yes I just noticed fixing it right now

**Pull request merged**
