### PR TITLE
Add time zone toggle to configure schedule in different time zones

### PR DESCRIPTION
**Pull request by ingridt123**
Creates dropdown in settings to select from all time zones (which changes all below based on dropdown selection)
- Course schedule times and days
- Course description times and days
- Print course schedule times and days
- Import/export JSON code courses times and days

### CODE REVIEW

**Comment by kwshi** [comment]
It seems like there are a few small issues--

- Upon refreshing the page, the selected time _zone_ stays the same, but the location associated with it may not.  For instance, if I select "eastern time (GMT-5)", refreshing gives "Bogota, Lima, Quito, Rio Branco (GMT-5)".  This is slightly eyebrow-raising, though it does not affect the core functionality.
- Is the time zone also exported in the JSON?  Or are the timezone-adjusted times for the courses exported directly?  What if I
  1. set my time zone to something non-default, like eastern time, then
  2. export JSON, then
  3. start a new session (say, incognito, or another computer) _without_ changing the time zone (i.e. use the default), and then
  4. import the JSON--
  Will the courses be imported with the correct times?  Or will they be imported with the pre-adjusted times, but then in the wrong time zone?

Apart from those two things, this looks great!  Thanks so much for the work!

**Comment by kwshi** [comment]
I'd like to make a recommendation to always _store the courses in the same "standard" time zone_ (probably PST), and only adjust for time zone in the rendering steps (adjust the HTML labels).  That would save us from having to worry about time zones in the exported JSON course data, since all TZ conversions only happen on the "visual" side.

**Comment by ingridt123** [comment]
Yeah I agree I think that is probably the most clear/easy. On another note, I was thinking that it might be nice to add time zone for the iCal export since it currently exports the times as "floating" (so whatever time zone a user's computer is configured to, a 9:15am PST would be 9:15am in their time zone).

**Comment by ingridt123** [comment]
Just FYI all the comments should be addressed. I can do the iCal change in a separate PR. Thanks!

Update: I've skimmed through the ics code and I don't think configuring time zone has been implemented yet.

**Comment by kwshi** [comment]
Nice!  This is great.  Thanks!

**Pull request merged**
